// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMpzKQo_4znwVNb2zndgFZvfeVfWNXb70',
    appId: '1:59614630867:web:4025c6b9fe41cfccbd1526',
    messagingSenderId: '59614630867',
    projectId: 'chatify-8cc32',
    authDomain: 'chatify-8cc32.firebaseapp.com',
    storageBucket: 'chatify-8cc32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1ugKinjuSWIpkvpaD7CrMmdnz6oVlfY',
    appId: '1:59614630867:android:e47eda83a34d7d02bd1526',
    messagingSenderId: '59614630867',
    projectId: 'chatify-8cc32',
    storageBucket: 'chatify-8cc32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbYrK66Xlc2bwsI3kMk_-7uHkx_hnzPlg',
    appId: '1:59614630867:ios:d52fe7358db06b2ebd1526',
    messagingSenderId: '59614630867',
    projectId: 'chatify-8cc32',
    storageBucket: 'chatify-8cc32.appspot.com',
    iosBundleId: 'com.example.chatify',
  );
}
